project_id = "fyfeyolecqnpriwjgzyo"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.natively-geolocation]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.paystack-webhook]
    verify_jwt = false
  [functions.paystack-initialize]
    verify_jwt = true
  [functions.paystack-verify]
    verify_jwt = true
  [functions.paystack-subaccount]
    verify_jwt = true
  [functions.paystack-banks]
    verify_jwt = true
  [functions.shippo-webhook]
    verify_jwt = false
  [functions.shippo-purchase-label]
    verify_jwt = false
  [functions.get-shipping-rates]
    verify_jwt = true

