import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import AdminEmptyState from "@/components/admin/AdminEmptyState";
import { RotateCcw, Search } from "lucide-react";
import { toast } from "sonner";
const AdminReturns=()=>{const qc=useQueryClient();const[filter,setFilter]=useState("");const[busy,setBusy]=useState<string|null>(null);
const{data:rows=[]}=useQuery({queryKey:["admin-returns"],queryFn:async()=>{const{data,error}=await supabase.from("return_requests" as any).select("*, orders(id, payment_status, paystack_reference), order_items(id, price, quantity, refunded_amount, products(name), vendors(store_name))").order("created_at",{ascending:false});if(error)throw error;return(data||[])as any[]}});
const filtered=rows.filter((r:any)=>[r.id,r.order_id,r.status,r.reason,r.order_items?.products?.name,r.order_items?.vendors?.store_name].filter(Boolean).join(" ").toLowerCase().includes(filter.toLowerCase()));
const REFUNDABLE=["approved","received","inspected","refund_approved"];
const refund=async(id:string)=>{setBusy(id);try{const{data,error}=await supabase.functions.invoke("paystack-refund",{body:{return_request_id:id}});if(error)throw error;toast.success(data?.duplicate?"Refund was already submitted.":data?.status==="processed"?"Refund confirmed by Paystack.":"Refund submitted — waiting for Paystack to confirm settlement.");await qc.invalidateQueries({queryKey:["admin-returns"]})}catch(e:any){toast.error(e?.message||"Refund failed. No status was changed.")}finally{setBusy(null)}};
return <div><AdminPageHeader title="Returns & Refunds" subtitle="Review approved returns and execute verified Paystack refunds." count={filtered.length} countLabel="returns"><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground"/><Input className="pl-9 h-9 bg-card" placeholder="Search returns..." value={filter} onChange={e=>setFilter(e.target.value)}/></div></AdminPageHeader>
{filtered.length===0?<div className="admin-card"><AdminEmptyState icon={RotateCcw} title="No returns found" description="Return requests will appear here for review and refund processing."/></div>:<div className="admin-card overflow-x-auto"><table className="admin-table"><thead><tr><th>Return</th><th>Order</th><th>Product / Vendor</th><th>Amount</th><th>Status</th><th>Reason</th><th>Action</th></tr></thead><tbody>{filtered.map((r:any)=>{const item=r.order_items;const remaining=Math.max(0,Number(item?.price||0)*Number(item?.quantity||0)-Number(item?.refunded_amount||0));return <tr key={r.id}><td className="font-mono text-xs">#{r.id.slice(0,8)}</td><td className="font-mono text-xs">#{String(r.order_id).slice(0,8)}</td><td><div className="font-medium">{item?.products?.name||"—"}</div><div className="text-xs text-muted-foreground">{item?.vendors?.store_name||"—"}</div></td><td>${remaining.toLocaleString()}</td><td><span className="status-pill bg-muted text-muted-foreground">{r.status}</span></td><td className="max-w-xs text-xs text-muted-foreground">{r.reason||"—"}</td><td>{REFUNDABLE.includes(r.status)?<Button size="sm" disabled={busy===r.id||remaining<=0} onClick={()=>refund(r.id)}>{busy===r.id?"Refunding…":"Refund via Paystack"}</Button>:r.status==="refunded"?<span className="text-xs text-success font-medium">Refunded</span>:r.status==="refund_processing"?<span className="text-xs text-muted-foreground">Awaiting Paystack confirmation</span>:<span className="text-xs text-muted-foreground">Awaiting approval</span>}</td></tr>})}</tbody></table></div>}</div>};
export default AdminReturns;